name: Build site

on:
  workflow_dispatch:
    branches:
      - '**'
  push:
    branches:
      - '**'
      - '!develop'
    paths-ignore:
      - '**/*.md'
      - '**/*.json'
      - '**/*.txt'
      - '**/*.ico'
      - '**/*.yml'
      - '**/*.editorconfig'
  pull_request:
    branches:
      - '**'
      - '!develop'
    paths-ignore:
      - '**/*.md'
      - '**/*.json'
      - '**/*.txt'
      - '**/*.ico'
      - '**/*.yml'
      - '**/*.editorconfig'

jobs:
  build_and_run_tests:
    name: Build C# code and run tests
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false

    steps:
      - name: Dump Environment when running locally
        if: ${{ env.ACT }}
        run:  env | sort

      - name: Get the sources
        uses: actions/checkout@v2

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v1

      - name: Restore NuGet packages
        run: dotnet restore ./src/henrikrxn.github.io.sln

      - name: Build solution
        run: dotnet build ./src/henrikrxn.github.io.sln --configuration Release --no-restore

      - name: Run tests from solution
        run: dotnet test ./src/henrikrxn.github.io.sln --no-restore --no-build
