name: Build site

on:
  push:
    branches:
      - '**'
      - '!develop'
  pull_request:
    branches:
      - '**'
      - '!develop'
    paths-ignore:
      - '**/*.md'
      - '**/*.json'
      - '**/*.txt'
      - '**/*.ico'
      - '**/*.yml'
      - '**/*.editorconfig'

jobs:
  build_and_run_tests:
    name: Build C# code and run tests
    runs-on: ubuntu-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v2

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v1

      - run: dotnet test ./src/henrikrxn.github.io.sln
