name: Deploy Site
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: "Deploy site"
    runs-on: windows-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v2

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v1

      - run: dotnet run --project ./src/henrikrxn.github.io -- deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

