name: Deploy Site
on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v2

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v1

      - run: dotnet run --project ./src/henrikrxn.github.io -- deploy

