# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Deploy Site

on:
  workflow_dispatch:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy site
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false

    steps:
      - name: Dump Environment when running locally
        if: ${{ env.ACT }}
        run:  env | sort

      - name: Get the sources
        uses: actions/checkout@v3.3.0
        with:
          submodules: recursive

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        id: dotnetsdk
        with:
          global-json-file: ./global.json

      - run: echo '${{ steps.dotnetsdk.outputs.dotnet-version }}'

      - name: Restore NuGet packages
        run: dotnet restore ./src/henrikrxn.github.io.sln

      - name: Build solution
        run: dotnet build ./src/henrikrxn.github.io.sln --configuration Release --no-restore

      - name: Run tests from solution
        run: dotnet test ./src/henrikrxn.github.io.sln --no-restore --no-build

      - name: Build and deploy locally
        if: ${{ env.ACT }}
        run: dotnet run --project ./src/henrikrxn.github.io -- deploy

      - name: Build and deploy
        if: ${{ !env.ACT }}
        run: dotnet run --project ./src/henrikrxn.github.io -- deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
